[versions]
gradle = "8.13"
jvmVersion = "8"

targetSdk = "35"
compileSdk = "35"
minSdk = "21"

agpVersion = "8.9.1"
kotlinVersion = "2.1.20"

dokkaVersion = "1.9.20"
appcompatVersion = "1.7.0"
recyclerviewVersion = "1.4.0"
viewPager2Version = "1.1.0"
swiperefreshlayoutVersion = "1.1.0"
annotationVersion = "1.6.0"
testRunnerVersion = "1.6.2"
testRulesVersion = "1.6.1"

espressoVersion = "3.6.1"

junitVersion = "4.13.2"
junitExtVersion = "1.2.1"
multidexVersion = "2.0.1"
materialVersion = "1.12.0"

detekt = "1.17.1"

githubApiVersion = "1.318"

[libraries]
com-android-tools-build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agpVersion" }
org-jetbrains-kotlin-kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinVersion" }

com-google-android-material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerviewVersion" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewPager2Version" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayoutVersion" }

androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoVersion" }
androidx-test-espresso-web = { group = "androidx.test.espresso", name = "espresso-web", version.ref = "espressoVersion" }
androidx-test-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espressoVersion" }
androidx-test-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espressoVersion" }

androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotationVersion" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunnerVersion" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRulesVersion" }

junit-junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExtVersion" }

androidx-multidex-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidexVersion" }

org-jetbrains-dokka-kotlinAsJavaPlugin = { group = "org.jetbrains.dokka", name = "kotlin-as-java-plugin", version.ref = "dokkaVersion" }
org-jetbrains-dokka-dokkaGradlePlugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokkaVersion" }

org-kohsuke-githubApi = { group = "org.kohsuke", name = "github-api", version.ref = "githubApiVersion" }
